language: node_js
node_js: "12"
branches:
  only:
    - master
    - main
    - model-folder
cache:
  directories:
    - node_modules
services:
  - mysql
# //before_install:
# //  - mysql -e 'CREATE DATABASE IF NOT EXISTS testdb;'

  # // make a small change to the project...
